# Generated by Django 4.2.6 on 2024-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstn', models.CharField(max_length=255)),
                ('lastn', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('academiclevel', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('hobby', models.CharField(max_length=255)),
                ('club', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
